### ISSUE TITLE
Go 1.16 required? undefined: os.MkdirTemp

### ISSUE THREAD

**Issue by tcullum-rh** [mcoops/deplist#40]
Hi,

I am using go version go1.15.15 linux/amd64 which is the latest version on Fedora 33 base repository.

When I try to make or otherwise use deplist, I get this error:

```
internal/scan/ruby.go:19:18: undefined: os.MkdirTemp
make: *** [Makefile:4: build] Error 2
```

I was able to work around this by going to https://github.com/mcoops/deplist/blob/783af3bd50cebe19210bbcd61992e2f2353f3205/internal/scan/ruby.go#L19 and changing it to: `gemPath, err := ioutil.TempDir("", "gem_vendor")` plus of course adding the import for `io/ioutil`.

I discovered this after locating: https://github.com/golang/go/issues/42026 . Seems Go 1.16 is required. Just wanted to mention it.

**Comment by mcoops** [comment]
+1 we've been finding that a bit and should've fixed it soon

https://github.com/mcoops/deplist/commit/5055d7e1fdd4995fbe55ad0816a69ddc44a7a1d0 should help address this
